# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: true


trigger:
  branches:  
    include:      
    - develop
    - main
    - feature/*
  paths:
    include:
    - src/BuildingBlocks/**    
    - src/Services/CoreProducts/**
    - deploy/core-products-azure-pipelines.yml
    - deploy/containerapps/modules/apps/core-products-api.bicep


pool:
  name: Default

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  applicationName: platform
  azureSubscription: platform-services-prod-asc
  serviceName: core-products-api
  repositoryName: core-products.api

stages:
- template: templates/container-app-stages.yml  # Template reference
  parameters:
    serviceName: 'core-products-api'
